version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672 # RabbitMQ port for AMQP communication
      - 15672:15672 # RabbitMQ Management UI port
    networks:
      - my_network

  m1:
    build:
      context: .
      dockerfile: ./m1/Dockerfile
    ports:
      - 3000:3000 # Expose M1 port
    networks:
      - my_network
    depends_on:
      - rabbitmq

  m2:
    restart: always
    build:
      context: .
      dockerfile: ./m2/Dockerfile
    networks:
      - my_network
    depends_on:
      - rabbitmq


networks:
  my_network:
